name: codebreaker
favicon: null
layout_spectrum: 0.50193
typography_spectrum: 0.3237
title: Code Breaker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
