analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.125
  rhythmicContrast: 0.25
  saturation: 0.3125
cta: {}
layout_spectrum: 0.50193
name: codebreaker
opengraph: {}
purpose: []
typography_spectrum: 0.3237
