name: codebreaker
favicon: null
layout_spectrum: 0.6876057060435414
typography_spectrum: 0.6367622874677181
title: Code Breaker
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.511079662013799
  lightness: 0.10366612183861434
  saturation: 0.19294531596824527
  rhythmicContrast: 0.47769326251000166
purpose: []
